#!/bin/bash
# /etc/init.d/smsserver

### BEGIN INIT INFO
# Provides:          smsserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage SMS Server
### END INIT INFO


case "$1" in 
    start)
        echo "Starting SMS Server"
        /home/pi/sms/smsserver.py
        ;;
    stop)
        echo "Stopping SMS Server"
        killall smsserver
        ;;
    *)
        echo "Usage: /etc/init.d/smsserver start|stop"
        exit 1
        ;;
esac

exit 0
